/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Fox({currentAnimation, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fox.glb')
  const { actions } = useAnimations(animations, group);
  

  useEffect(() => {
    const allActions = [
        'Cube.001Action',
        'Cube.002Action',
        'Cube.003Action',
        'Cube.004Action',
        'Cube.005Action',
        'Cube.006Action',
        'Cube.007Action',
        'Cube.008Action',
        'Cube.009Action',
        'CubeAction'
    ]
    allActions.forEach(actionName => {
        const action = actions[actionName];
        if (action) {
            action.reset().stop();
        }
    })

    switch(currentAnimation) {
        case 'idle':
            break;
        case 'walk':
            allActions.forEach(actionName => {
                const action = actions[actionName];
                if (action) {
                    action.timeScale = 0.5
                    action.play();
                }
            })
            break;
        case 'run':
            allActions.forEach(actionName => {
                const action = actions[actionName];
                if (action) {
                    action.timeScale = 1;
                    action.play();
                }
            })
            break;
    }
    return () => {
        allActions.forEach(actionName => {
            const action = actions[actionName];
            if (action) {
                action.stop();
            }
        })
    }
  }, [actions, currentAnimation])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Fox"
          castShadow
          receiveShadow
          geometry={nodes.Fox.geometry}
          material={materials.Material}
          scale={[5.452, 2.974, 2.974]}>
          <group name="Head" position={[-1.544, 0.332, 0.008]} scale={[0.545, 1, 1.333]}>
            <mesh
              name="Cube001"
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={materials.Material}
            />
            <mesh
              name="Cube001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Cube001_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_2.geometry}
              material={materials['Material.002']}
            />
            <group name="Mice" position={[-1.464, -0.667, -0.001]} scale={[0.471, 0.333, 0.5]}>
              <mesh
                name="Cube003"
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                material={materials.Material}
              />
              <mesh
                name="Cube003_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_1.geometry}
                material={materials['Material.003']}
              />
            </group>
            <mesh
              name="UHO"
              castShadow
              receiveShadow
              geometry={nodes.UHO.geometry}
              material={materials.Material}
              position={[-0.51, 1.331, -0.751]}
              scale={[0.167, 0.334, 0.25]}
            />
            <mesh
              name="UHO2"
              castShadow
              receiveShadow
              geometry={nodes.UHO2.geometry}
              material={materials.Material}
              position={[-0.503, 1.331, 0.755]}
              rotation={[0, 0, -Math.PI]}
              scale={[-0.167, -0.334, -0.25]}
            />
          </group>
          <mesh
            name="Hvost"
            castShadow
            receiveShadow
            geometry={nodes.Hvost.geometry}
            material={materials.Material}
            position={[0.99, -0.038, -0.024]}
            scale={[0.816, 0.665, 0.665]}
          />
          <mesh
            name="LegL1"
            castShadow
            receiveShadow
            geometry={nodes.LegL1.geometry}
            material={materials.Material}
            position={[-0.699, -0.781, 0.711]}
            rotation={[0, 0, -0.55]}
            scale={[0.235, 0.87, 0.319]}
          />
          <mesh
            name="LegL2"
            castShadow
            receiveShadow
            geometry={nodes.LegL2.geometry}
            material={materials.Material}
            position={[0.576, -0.781, 0.764]}
            rotation={[0, 0, 0.55]}
            scale={[0.235, 0.87, 0.319]}
          />
          <mesh
            name="LegR1"
            castShadow
            receiveShadow
            geometry={nodes.LegR1.geometry}
            material={materials.Material}
            position={[-0.664, -0.781, -0.684]}
            rotation={[0, 0, -2.592]}
            scale={[-0.235, -0.87, -0.319]}
          />
          <mesh
            name="LegR2"
            castShadow
            receiveShadow
            geometry={nodes.LegR2.geometry}
            material={materials.Material}
            position={[0.63, -0.781, -0.714]}
            rotation={[0, 0, 2.592]}
            scale={[-0.235, -0.87, -0.319]}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/fox.glb')
